name: Greetings

on: 
  pull_request:
    types: opened
  issues:
    types: opened

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Welcome! If this is a security issue, please send details to odyssey346@disroot.org, or message us on Discord. We also request you to be patient.'
        pr-message: 'Thanks for your contribution! Make sure you''ve [checked the docs], and wait for a review!'
